version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:1.6.12
    container_name: mosquitto-broker
    restart: always
    ports:
      - "1841:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    user: "1883:1883"
